language: node_js
node_js:
  - 'node' # use latest stable nodejs version
script:
  - npm test  # test build to build and run ava tests
  - npm run coverage  # generate nyc report
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
